### ISSUE TITLE
Build error: File `substitutefont.sty' not found

### ISSUE THREAD

**Issue by SHtress** [ostis-ai/ostis-standard#381]
**Describe the bug**
File `substitutefont.sty' not found.
https://www.ctan.org/pkg/substitutefont

**To Reproduce**
Try to build book.tex

**Expected behavior**
Successful build

**Screenshots**
![image](https://github.com/ostis-ai/ostis-standard/assets/44646393/52d2ac2a-8af1-4b04-90cd-eb139968ce6e)

**Additional context**
Build on Windows 10, TeXstudio

**Comment by ShunkevichDV** [comment]
Suggested solution:

% Курсив и жирность для кириллицы

\DeclareFontFamilySubstitution{T2A}{\familydefault}{Tempora-TLF}
\makeatletter
\input{t2atempora-tlf.fd}
\DeclareFontShape{T2A}{Tempora-TLF}{m}{sc}{
    <-> ssub * Tempora-TLF/m/n
}{}

**Comment by SHtress** [comment]
For quick fix on Windows you can download this package manually and install by this guide https://tex.stackexchange.com/questions/558658/how-do-i-install-packages-in-texlive-on-windows-10

P.S. But this package is obsolete so I create PR with workings solution suggested by @ShunkevichDV
